# Site settings
title: dlans321
url: https://dlans321.github.io
lang: ko_KR
timezone: Asia/Seoul
image: /assets/image/site/profile.jpg

# Author
Author:
  name: dlans321
  email: dlans321@naver.com
  url: https://dlans321.github.io

# Build settings
markdown: kramdown

# Gems
plugins: 
  - jekyll-paginate-v2

# pagination
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 7
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    atfer: 2



